language: java
jdk:
  - openjdk7

services:
  - docker

sudo: required
services:
  - docker

cache:
  directories:
    - '$HOME/.m2'

jobs:
  include:
    script:
	     -	mvn clean install -B -Dtest=FunctionalTestSuite
