language: java
jdk:
  - openjdk7

env:
  - MAVEN_HOME=/usr/local/maven

services:
  - docker

sudo: required
services:
  - docker

cache:
  directories:
    - '$HOME/.m2'

install: mvn test -Dtest=FunctionalTestSuite
